import { Pipe, PipeTransform, inject } from '@angular/core';
import { ThemeService } from '../services/theme.service';

const DICTIONARY: Record<string, Record<string, string>> = {
  en: {
    'Explorar': 'Explore',
    'Agenda': 'Agenda',
    'Eventos': 'Events',
    'Favoritos': 'Favorites',
    'Planes': 'Plans',
    'Promos': 'Promotions',
    'Ofertas': 'Offers',
    'Mi Perfil': 'My Profile',
    'Crear Lugar': 'Create Place',
    'Crear Evento': 'Create Event',
    'Ingresar': 'Sign In',
    'Crear cuenta': 'Sign Up',
    'Empezar': 'Get Started',
    'Salir': 'Logout',
    'Configuración': 'Settings',
    'Preferencias': 'Preferences',
    'Categorías de eventos favoritas:': 'Favorite event categories:',
    'Selecciona las categorías que te interesen': 'Select the categories you are interested in',
    'Notificaciones:': 'Notifications:',
    'Activar notificaciones': 'Enable notifications',
    'Notificaciones por email': 'Email notifications',
    'Apariencia:': 'Appearance:',
    'Claro': 'Light',
    'Oscuro': 'Dark',
    'Automático': 'Automatic',
    'Idioma:': 'Language:',
    'Español': 'Spanish',
    'English': 'English',
    'Tamaño de fuente:': 'Font size:',
    'Pequeño': 'Small',
    'Mediano': 'Medium',
    'Grande': 'Large',
    'Guardar cambios': 'Save changes',
    'Guardando...': 'Saving...',
    'Historial de planes consultados': 'Consulted plans history',
    'Limpiar': 'Clear',
    'Cargando historial...': 'Loading history...',
    'No existen planes consultados.': 'There are no consulted plans.',
    '¡Explora lugares y eventos para ver tu historial aquí!': 'Explore places and events to see your history here!',
    'Sin descripción': 'No description',
    '⚠️ Cambios sin guardar': '⚠️ Unsaved changes',
    'Tienes cambios en tus preferencias que no has guardado. ¿Seguro que quieres salir?': 'You have unsaved changes in your preferences. Are you sure you want to leave?',
    'Cancelar': 'Cancel',
    'Salir sin guardar': 'Leave without saving',
    'Información Personal': 'Personal Information',
    'Nombre Completo': 'Full Name',
    'Teléfono': 'Phone',
    'Foto de perfil': 'Profile Picture',
    'Arrastra una imagen o haz clic para buscar': 'Drag an image or click to browse',
    'Guardar Cambios': 'Save Changes',
    'Mi Suscripción': 'My Subscription',
    'Renovar o cambiar plan': 'Renew or change plan',
    'Panel de Propietario': 'Owner Panel',
    'Lugares': 'Places',
    'Visitas': 'Visits',
    'Crear Nuevo Lugar': 'Create New Place',
    'Mis Lugares': 'My Places',
    'Mis Eventos': 'My Events',
    'Aún no has creado ningún lugar': 'You have not created any places yet',
    'Crear mi primer lugar': 'Create my first place',
    'Ver público': 'View public',
    'Editar': 'Edit',
    'Mis Favoritos': 'My Favorites',
    'No tienes favoritos aún': 'You have no favorites yet',
    'Explorar lugares': 'Explore places',
    '¿Quieres agregar tus propios lugares?': 'Do you want to add your own places?',
    'Convierte tu cuenta en Owner y comienza a publicar': 'Convert your account to Owner and start publishing',
    'Ver Planes': 'View Plans',
    'Cargando perfil...': 'Loading profile...',
    'Eventos:': 'Events:',
    'Publicado': 'Published',
    'Borrador': 'Draft',
    'Activo': 'Active',
    'Usuario': 'User',
    'Administrador': 'Admin',
    'Propietario': 'Owner',
    'Calibrar ubicación de búsqueda...': 'Calibrate search location...',
    'Buscar': 'Search',
    'Mi ubicación': 'My location',
    'Tu Próximo Destino': 'Your Next Destination',
    'Explora lo que te define': 'Explore what defines you',
    'Descubre los rincones más auténticos de la ciudad...': 'Discover the most authentic corners of the city...',
    'Geo-localizado': 'Geo-localized',
    'Curado': 'Curated',
    'Tiempo Real': 'Real Time',
    'Nombre': 'Name',
    'Buscar lugar...': 'Search place...',
    'Ciudad': 'City',
    'Todas las ciudades': 'All cities',
    'Interés': 'Interest',
    'Todos los tipos': 'All types',
    'Presupuesto': 'Budget',
    'Cualquier nivel': 'Any level',
    'Abierto ahora': 'Open now',
    'Actualizar Radar': 'Update Radar',
    'Sincronizando radar...': 'Synchronizing radar...',
    'Sin señales': 'No signals',
    'Ajusta tu radar para encontrar nuevos lugares.': 'Adjust your radar to find new places.',
    'Lugar': 'Place',
    'Sin descripción disponible': 'No description available',
    'Ver Detalle': 'View Detail',
    'Cómo llegar': 'Get directions',
    'Quitar favorito': 'Remove favorite',
    'Guardar': 'Save',
    'Calibración de Explorador': 'Explorer Calibration',
    'Intereses y Radar': 'Interests and Radar',
    'Personaliza cómo Ubica2 encuentra gemas para ti.': 'Customize how Ubica2 finds gems for you.',
    'Categorías Favoritas': 'Favorite Categories',
    'Canales de Pulso': 'Pulse Channels',
    'Notificaciones del Sistema': 'System Notifications',
    'Resúmenes por Email': 'Email Summaries',
    'Rastro de Descubrimientos': 'Trail of Discoveries',
    'Tu camino reciente por la ciudad.': 'Your recent path through the city.',
    'Limpiar Rastro': 'Clear Trail',
    'Leyendo rastro...': 'Reading trail...',
    'Tu rastro está vacío. Empieza a explorar.': 'Your trail is empty. Start exploring.',
    'Visión': 'Vision',
    'Escala de Interfaz': 'Interface Scale',
    'Guardar Calibración': 'Save Calibration',
    'Sincronizando...': 'Synchronizing...',
    'Evento': 'Event'
  }
};

@Pipe({
  name: 'translate',
  standalone: true,
  pure: false // False because we want it to update when the ThemeService language changes
})
export class TranslatePipe implements PipeTransform {
  private readonly themeService = inject(ThemeService);

  transform(key: string): string {
    const lang = this.themeService.currentLanguage();
    
    if (lang === 'es' || !DICTIONARY[lang]) {
      return key; // Default to Spanish (the key itself)
    }

    return DICTIONARY[lang][key] || key;
  }
}
